version: "3"

services:
    node:
        container_name: node-dev
        image: node:latest
        ports:
            # only map localhost-port
            - "8080:8080"
        volumes:
            - ${DIR_FRONT_END}:/front_end
        entrypoint: 
            - "/bin/bash"
        command: -c "cd /front_end && npm run dev"

    hicognition:
        container_name: flask-dev
        volumes:  
            - ${HICOGNITION_DIR}:/code # quick and dirty mount of the git repo
            # TODO fix this, this is horrible
            # #HICOGNITION_DIR=./workdir/hicognition_dir -> use for path of DB
        environment:
            - UPLOAD_ENABLED=true
            - PUBLIC_UPLOAD_ENABLED=true
            - FLASK_DEBUG=1
            - FLASK_APP=/code/hicognition_server.py
            - HIGLASS_USER=${DJANGO_SUPERUSER}
            - HIGLASS_PWD=${DJANGO_SUPERUSER_PASSWORD}
            - REDIS_URL=${REDIS_URL}
            - UPLOAD_DIR=${UPLOAD_DIR}
            - CHROM_SIZES=${CHROM_SIZES}
            - CHROM_ARMS=${CHROM_ARMS}
        ports:
            # only map localhost-port
            - "5000:5000"
        build:
            context: "./back_end"
        image: flask:test2
            # TODO Host this on Dockerhub
        entrypoint: "/bin/bash"
        networks:
            hicognition-net:
                ipv4_address: 172.18.0.3
        command: -c "source activate flask && cd /code && flask db upgrade && flask run --host=0.0.0.0"


    redis-server:
        container_name: redis-server
        image: redis:3-alpine
        networks:
            hicognition-net:
                ipv4_address: 172.18.0.4
        ports:
            - 6379:6379

    redis-worker:
        container_name: redis-worker
        volumes:  
            - ${HICOGNITION_DIR}:/code # quick and dirty mount of the git repo
            # TODO fix this, this is horrible
            # #HICOGNITION_DIR=./workdir/hicognition_dir -> use for path of DB
        environment:
            - UPLOAD_ENABLED=true
            - PUBLIC_UPLOAD_ENABLED=true
            - FLASK_DEBUG=1
            - FLASK_APP=/code/hicognition_server.py
            - HIGLASS_USER=${DJANGO_SUPERUSER}
            - HIGLASS_PWD=${DJANGO_SUPERUSER_PASSWORD}
            - REDIS_URL=${REDIS_URL}
            - CHROM_SIZES=${CHROM_SIZES}
            - CHROM_ARMS=${CHROM_ARMS}
        build:
            context: "./back_end"
        image: flask:test2
            # TODO Host this on Dockerhub
        entrypoint: "/bin/bash"
        networks:
            hicognition-net:
                ipv4_address: 172.18.0.5
        command: -c "source activate flask && cd /code/ && rq worker -u ${REDIS_URL} hicognition-tasks"


    # higlass server
    higlass:
        container_name: higlass-container
        image: higlass/higlass-docker
        environment:
            - UPLOAD_ENABLED=true
            - PUBLIC_UPLOAD_ENABLED=true
        volumes:
            - ${DATA_DIR}:/data
            - ${HIGLASS_TMP}:/tmp
        ports:
            - "8888:80"
        networks:
            hicognition-net:
                ipv4_address: 172.18.0.2

networks:
    hicognition-net:
        ipam:
            driver: default
            config:
                - subnet: 172.18.0.0/16