version: "3"

services:
    # flask-api server
    hicognition:
        container_name: flask-server
        volumes:  
            - ${HICOGNITION_DIR}:/code
        environment:
            - FLASK_DEBUG=0
            - FLASK_APP=/code/hicognition_server.py
            - DATABASE_URL=${DATABASE_URL}
            - REDIS_URL=${REDIS_URL}
            - UPLOAD_DIR=${UPLOAD_DIR}
            - CHROM_SIZES=${CHROM_SIZES}
            - CHROM_ARMS=${CHROM_ARMS}
        ports:
            # only map localhost-port
            - "5000:5000"
        build:
            context: "./back_end"
        image: flask:v1.0
        entrypoint: "/bin/bash"
        command: -c "cd /code && ./boot.sh"
        networks:
            hicognition-net:
                ipv4_address: 172.18.0.3

    # nginx server to serve front-end and redirect requests to flask-api
    nginx:
        container_name: hicognition-nginx
        build:
            context: "./nginx"
        ports:
            - "80:80"
        # map front-end files
        depends_on:
            - node
            - hicognition
        volumes:
            - ${DIR_FRONT_END}:/front_end
            - ${DIR_STATIC}:/static
            - ${KEY_DIR}:/keys
        networks:
            - hicognition-net

    # container to build front-end
    node:
        container_name: node-builder
        image: node:14-buster
        volumes:
            - ${DIR_FRONT_END}:/front_end
        entrypoint: 
            - "/bin/bash"
        command: -c "cd /front_end && npm install && npm run build"

    redis-server:
        container_name: redis-server
        build:
            context: "./redis"
        networks:
            hicognition-net:
                ipv4_address: 172.18.0.5
        ports:
            - 6379:6379

    redis-worker:
        container_name: redis-worker
        volumes:  
            - ${HICOGNITION_DIR}:/code
        environment:
            - FLASK_DEBUG=1
            - FLASK_APP=/code/hicognition_server.py
            - DATABASE_URL=${DATABASE_URL}
            - REDIS_URL=${REDIS_URL}
            - UPLOAD_DIR=${UPLOAD_DIR}
            - CHROM_SIZES=${CHROM_SIZES}
            - CHROM_ARMS=${CHROM_ARMS}
        depends_on:
                - redis-server
        build:
            context: "./back_end"
        image: flask:v1.0
        entrypoint: "/bin/bash"
        networks:
            hicognition-net:
                ipv4_address: 172.18.0.6
        # sleeps to wait for redis-server. TODO: make this check nicer!
        command: -c "sleep 5 && cd /code/ && rq worker -u ${REDIS_URL} hicognition-tasks"

    redis-worker2:
        container_name: redis-worker2
        volumes:  
            - ${HICOGNITION_DIR}:/code
        environment:
            - FLASK_DEBUG=1
            - FLASK_APP=/code/hicognition_server.py
            - DATABASE_URL=${DATABASE_URL}
            - REDIS_URL=${REDIS_URL}
            - UPLOAD_DIR=${UPLOAD_DIR}
            - CHROM_SIZES=${CHROM_SIZES}
            - CHROM_ARMS=${CHROM_ARMS}
        depends_on:
                - redis-server
        build:
            context: "./back_end"
        image: flask:v1.0
        entrypoint: "/bin/bash"
        networks:
            hicognition-net:
                ipv4_address: 172.18.0.7
        # sleeps to wait for redis-server. TODO: make this check nicer!
        command: -c "sleep 5 && cd /code/ && rq worker -u ${REDIS_URL} hicognition-tasks"

    redis-worker3:
        container_name: redis-worker3
        volumes:  
            - ${HICOGNITION_DIR}:/code
        environment:
            - FLASK_DEBUG=1
            - FLASK_APP=/code/hicognition_server.py
            - DATABASE_URL=${DATABASE_URL}
            - REDIS_URL=${REDIS_URL}
            - UPLOAD_DIR=${UPLOAD_DIR}
            - CHROM_SIZES=${CHROM_SIZES}
            - CHROM_ARMS=${CHROM_ARMS}
        depends_on:
                - redis-server
        build:
            context: "./back_end"
        image: flask:v1.0
        entrypoint: "/bin/bash"
        networks:
            hicognition-net:
                ipv4_address: 172.18.0.8
        # sleeps to wait for redis-server. TODO: make this check nicer!
        command: -c "sleep 5 && cd /code/ && rq worker -u ${REDIS_URL} hicognition-tasks"

    mysql:
        container_name: mysql
        ports:
            # map port out for diagnostics
            - "3306:3306"
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
            - MYSQL_DATABASE=hicognition
            - MYSQL_USER=hicognition
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        image: mysql/mysql-server:8.0
        volumes:
            - ${MYSQL_DATA_DIR}:/var/lib/mysql
            - ./mysql/mysql.cnf:/etc/my.cnf
        networks:
            hicognition-net:
                ipv4_address: 172.18.0.9

networks:
    hicognition-net:
        ipam:
            driver: default
            config:
                - subnet: 172.18.0.0/16