version: "3"

services:
    # flask-api server
    hicognition:
        container_name: flask-server
        volumes:  
            - ${HICOGNITION_DIR}:/code # quick and dirty mount of the git repo
            # TODO fix this, this is horrible
            # #HICOGNITION_DIR=./workdir/hicognition_dir -> use for path of DB
        environment:
            - UPLOAD_ENABLED=true
            - PUBLIC_UPLOAD_ENABLED=true
            - FLASK_DEBUG=1
            - FLASK_APP=/code/hicognition_server.py
            - HIGLASS_USER=${DJANGO_SUPERUSER}
            - HIGLASS_PWD=${DJANGO_SUPERUSER_PASSWORD}
        depends_on:
            - higlass
        ports:
            # only map localhost-port
            - "127.0.0.1:5000:5000"
        build:
            context: "./back_end"
        image: flask:test2
            # TODO Host this on Dockerhub
        entrypoint: "/bin/bash"
        command: -c "source activate flask && cd /code && flask db upgrade && flask run --host=0.0.0.0"
        networks:
            hicognition-net:
                ipv4_address: 172.18.0.3

    # higlass server
    higlass:
        container_name: higlass-container
        image: higlass/higlass-docker
        environment:
            - UPLOAD_ENABLED=true
            - PUBLIC_UPLOAD_ENABLED=true
        volumes:
            - ${DATA_DIR}:/data
            - ${HIGLASS_TMP}:/tmp
        ports:
            - "8888:80"
        depends_on:
            - higlass-usercreation
        networks:
            hicognition-net:
                ipv4_address: 172.18.0.2

    # dummy higlass container to create superuser if it does not exist yet
    higlass-usercreation:
        container_name: higlass-container-usercreation
        image: higlass/higlass-docker
        environment:
            - UPLOAD_ENABLED=true
            - PUBLIC_UPLOAD_ENABLED=true
        volumes:
            - ${DATA_DIR}:/data
            - ${HIGLASS_TMP}:/tmp
            # this depends on the path to manage.py
        command: python /home/higlass/projects/higlass-server/manage.py shell -c "from django.contrib.auth.models import User;
                                                                                  User.objects.filter(username='${DJANGO_SUPERUSER}').exists() or User.objects.create_superuser('${DJANGO_SUPERUSER}',
                                                                                                                                                                                'admin1@example.com',
                                                                                                                                                                                '${DJANGO_SUPERUSER_PASSWORD}')"
    # nginx server to serve front-end and redirect requests to flask-api
    nginx:
        container_name: hicognition-nginx
        build:
            context: "./nginx"
        ports:
            - "80:80"
        # map front-end files
        depends_on:
            - node
            - hicognition
        volumes:
            - ${DIR_FRONT_END}:/front_end
        networks:
            hicognition-net:
                ipv4_address: 172.18.0.4

    # container to build front-end
    node:
        container_name: node-builder
        image: node:latest
        volumes:
            - ${DIR_FRONT_END}:/front_end
        entrypoint: 
            - "/bin/bash"
        command: -c "cd /front_end && npm install && npm run build"


networks:
    hicognition-net:
        ipam:
            driver: default
            config:
                - subnet: 172.18.0.0/16