version: "3"

services:
    node:
        container_name: node-dev
        image: node:14-buster
        ports:
            # only map localhost-port
            - "8080:8080"
        volumes:
            - ${DIR_FRONT_END}:/front_end
        entrypoint: 
            - "/bin/bash"
        command: -c "cd /front_end && npm install && npm run dev"

    hicognition:
        container_name: flask-dev
        volumes:  
            - ${HICOGNITION_DIR}:/code
        environment:
            - FLASK_DEBUG=1
            - FLASK_APP=/code/hicognition_server.py
            - REDIS_URL=${REDIS_URL}
            - UPLOAD_DIR=${UPLOAD_DIR}
            - CHROM_SIZES=${CHROM_SIZES}
            - CHROM_ARMS=${CHROM_ARMS}
        ports:
            # only map localhost-port
            - "5000:5000"
        build:
            context: "./back_end"
        image: flask:test2
        entrypoint: "/bin/bash"
        networks:
            hicognition-net:
                ipv4_address: 172.18.0.3
        command: -c "source activate flask && cd /code && flask db upgrade && flask run --host=0.0.0.0"


    redis-server:
        container_name: redis-server
        build:
            context: "./redis"
        networks:
            hicognition-net:
                ipv4_address: 172.18.0.4
        ports:
            - 6379:6379

    redis-worker:
        container_name: redis-worker
        volumes:  
            - ${HICOGNITION_DIR}:/code
        environment:
            - FLASK_DEBUG=1
            - FLASK_APP=/code/hicognition_server.py
            - REDIS_URL=${REDIS_URL}
            - UPLOAD_DIR=${UPLOAD_DIR}
            - CHROM_SIZES=${CHROM_SIZES}
            - CHROM_ARMS=${CHROM_ARMS}
        depends_on:
                - redis-server
        build:
            context: "./back_end"
        image: flask:test2
        entrypoint: "/bin/bash"
        networks:
            hicognition-net:
                ipv4_address: 172.18.0.5
        # sleeps to wait for redis-server. TODO: make this check nicer!
        command: -c "sleep 5 && source activate flask && cd /code/ && rq worker -u ${REDIS_URL} hicognition-tasks"

    redis-worker2:
        container_name: redis-worker2
        volumes:  
            - ${HICOGNITION_DIR}:/code
        environment:
            - FLASK_DEBUG=1
            - FLASK_APP=/code/hicognition_server.py
            - REDIS_URL=${REDIS_URL}
            - UPLOAD_DIR=${UPLOAD_DIR}
            - CHROM_SIZES=${CHROM_SIZES}
            - CHROM_ARMS=${CHROM_ARMS}
        depends_on:
                - redis-server
        build:
            context: "./back_end"
        image: flask:test2
        entrypoint: "/bin/bash"
        networks:
            hicognition-net:
                ipv4_address: 172.18.0.6
        # sleeps to wait for redis-server. TODO: make this check nicer!
        command: -c "sleep 5 && source activate flask && cd /code/ && rq worker -u ${REDIS_URL} hicognition-tasks"

    redis-worker3:
        container_name: redis-worker3
        volumes:  
            - ${HICOGNITION_DIR}:/code
        environment:
            - FLASK_DEBUG=1
            - FLASK_APP=/code/hicognition_server.py
            - REDIS_URL=${REDIS_URL}
            - UPLOAD_DIR=${UPLOAD_DIR}
            - CHROM_SIZES=${CHROM_SIZES}
            - CHROM_ARMS=${CHROM_ARMS}
        depends_on:
                - redis-server
        build:
            context: "./back_end"
        image: flask:test2
        entrypoint: "/bin/bash"
        networks:
            hicognition-net:
                ipv4_address: 172.18.0.7
        # sleeps to wait for redis-server. TODO: make this check nicer!
        command: -c "sleep 5 && source activate flask && cd /code/ && rq worker -u ${REDIS_URL} hicognition-tasks"


    redis-worker4:
        container_name: redis-worker4
        volumes:  
            - ${HICOGNITION_DIR}:/code
        environment:
            - FLASK_DEBUG=1
            - FLASK_APP=/code/hicognition_server.py
            - REDIS_URL=${REDIS_URL}
            - UPLOAD_DIR=${UPLOAD_DIR}
            - CHROM_SIZES=${CHROM_SIZES}
            - CHROM_ARMS=${CHROM_ARMS}
        depends_on:
                - redis-server
        build:
            context: "./back_end"
        image: flask:test2
        entrypoint: "/bin/bash"
        networks:
            hicognition-net:
                ipv4_address: 172.18.0.8
        # sleeps to wait for redis-server. TODO: make this check nicer!
        command: -c "sleep 5 && source activate flask && cd /code/ && rq worker -u ${REDIS_URL} hicognition-tasks"

    redis-worker5:
        container_name: redis-worker5
        volumes:  
            - ${HICOGNITION_DIR}:/code
        environment:
            - FLASK_DEBUG=1
            - FLASK_APP=/code/hicognition_server.py
            - REDIS_URL=${REDIS_URL}
            - UPLOAD_DIR=${UPLOAD_DIR}
            - CHROM_SIZES=${CHROM_SIZES}
            - CHROM_ARMS=${CHROM_ARMS}
        depends_on:
                - redis-server
        build:
            context: "./back_end"
        image: flask:test2
        entrypoint: "/bin/bash"
        networks:
            hicognition-net:
                ipv4_address: 172.18.0.9
        # sleeps to wait for redis-server. TODO: make this check nicer!
        command: -c "sleep 5 && source activate flask && cd /code/ && rq worker -u ${REDIS_URL} hicognition-tasks"

networks:
    hicognition-net:
        ipam:
            driver: default
            config:
                - subnet: 172.18.0.0/16