version: "3"

services:
    node:
        container_name: node-dev
        image: node:latest
        ports:
            # only map localhost-port
            - "8080:8080"
        volumes:
            - ${DIR_FRONT_END}:/front_end
        entrypoint: 
            - "/bin/bash"
        command: -c "cd /front_end && npm run dev"

    hicognition:
        container_name: flask-dev
        volumes:  
            - ${HICOGNITION_DIR}:/code # quick and dirty mount of the git repo
            # TODO fix this, this is horrible
            # #HICOGNITION_DIR=./workdir/hicognition_dir -> use for path of DB
        environment:
            - UPLOAD_ENABLED=true
            - PUBLIC_UPLOAD_ENABLED=true
            - FLASK_DEBUG=1
            - FLASK_APP=/code/hicognition_server.py
            - HIGLASS_USER=${DJANGO_SUPERUSER}
            - HIGLASS_PWD=${DJANGO_SUPERUSER_PASSWORD}
        ports:
            # only map localhost-port
            - "5000:5000"
        build:
            context: "./back_end"
        image: flask:test2
            # TODO Host this on Dockerhub
        entrypoint: "/bin/bash"
        command: -c "source activate flask && cd /code && flask db upgrade && flask run --host=0.0.0.0"