"""Added task relationship to collection

Revision ID: 096e3802a6db
Revises: 5ea96c0a7508
Create Date: 2021-07-28 08:51:36.373977

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "096e3802a6db"
down_revision = "5ea96c0a7508"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "session",
        "session_object",
        existing_type=mysql.LONGTEXT(),
        type_=sa.Text(length=1000000000),
        existing_nullable=True,
    )
    op.add_column("task", sa.Column("collection_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "task", "collection", ["collection_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "task", type_="foreignkey")
    op.drop_column("task", "collection_id")
    op.alter_column(
        "session",
        "session_object",
        existing_type=sa.Text(length=1000000000),
        type_=mysql.LONGTEXT(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
