"""added session table

Revision ID: 0fbd7ca83885
Revises: 64c188efd43d
Create Date: 2021-05-03 09:02:43.441307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fbd7ca83885'
down_revision = '64c188efd43d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_object', sa.String(length=1000), nullable=True),
    sa.Column('created_utc', sa.DateTime(), nullable=False),
    sa.Column('session_type', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_dataset_assoc_table',
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_dataset_assoc_table')
    op.drop_table('session')
    # ### end Alembic commands ###
