"""add user fk, removed by acc

Revision ID: 14fbe9254f05
Revises: 28a16cbebebf
Create Date: 2022-10-18 14:59:07.977580

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '14fbe9254f05'
down_revision = '28a16cbebebf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'dataset', 'user', ['user_id'], ['id'])
    op.alter_column('session', 'session_object',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=1000000000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session', 'session_object',
               existing_type=sa.Text(length=1000000000),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'dataset', type_='foreignkey')
    # ### end Alembic commands ###
