"""initial commit

Revision ID: 1d12fd16b35e
Revises: 
Create Date: 2020-10-06 09:12:09.298632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d12fd16b35e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('dataset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_name', sa.String(length=64), nullable=True),
    sa.Column('file_path', sa.String(length=128), nullable=True),
    sa.Column('higlass_uuid', sa.String(length=64), nullable=True),
    sa.Column('filetype', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_dataset_name'), 'dataset', ['dataset_name'], unique=True)
    op.create_index(op.f('ix_dataset_file_path'), 'dataset', ['file_path'], unique=True)
    op.create_index(op.f('ix_dataset_filetype'), 'dataset', ['filetype'], unique=False)
    op.create_index(op.f('ix_dataset_higlass_uuid'), 'dataset', ['higlass_uuid'], unique=True)
    op.create_table('pileupregion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('file_path', sa.String(length=128), nullable=True),
    sa.Column('higlass_uuid', sa.String(length=64), nullable=True),
    sa.Column('windowsize', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pileupregion_file_path'), 'pileupregion', ['file_path'], unique=False)
    op.create_index(op.f('ix_pileupregion_higlass_uuid'), 'pileupregion', ['higlass_uuid'], unique=False)
    op.create_index(op.f('ix_pileupregion_name'), 'pileupregion', ['name'], unique=True)
    op.create_index(op.f('ix_pileupregion_windowsize'), 'pileupregion', ['windowsize'], unique=False)
    op.create_table('pileup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('binsize', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('file_path', sa.String(length=128), nullable=True),
    sa.Column('cooler_id', sa.Integer(), nullable=True),
    sa.Column('pileupregion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cooler_id'], ['dataset.id'], ),
    sa.ForeignKeyConstraint(['pileupregion_id'], ['pileupregion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pileup_file_path'), 'pileup', ['file_path'], unique=False)
    op.create_index(op.f('ix_pileup_name'), 'pileup', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pileup_name'), table_name='pileup')
    op.drop_index(op.f('ix_pileup_file_path'), table_name='pileup')
    op.drop_table('pileup')
    op.drop_index(op.f('ix_pileupregion_windowsize'), table_name='pileupregion')
    op.drop_index(op.f('ix_pileupregion_name'), table_name='pileupregion')
    op.drop_index(op.f('ix_pileupregion_higlass_uuid'), table_name='pileupregion')
    op.drop_index(op.f('ix_pileupregion_file_path'), table_name='pileupregion')
    op.drop_table('pileupregion')
    op.drop_index(op.f('ix_dataset_higlass_uuid'), table_name='dataset')
    op.drop_index(op.f('ix_dataset_filetype'), table_name='dataset')
    op.drop_index(op.f('ix_dataset_file_path'), table_name='dataset')
    op.drop_index(op.f('ix_dataset_dataset_name'), table_name='dataset')
    op.drop_table('dataset')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
