"""added uwer-id to Assembly

Revision ID: 29e8d18e650b
Revises: 6a9c1bc13457
Create Date: 2021-08-26 10:59:53.016225

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '29e8d18e650b'
down_revision = '6a9c1bc13457'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assembly', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'assembly', 'user', ['user_id'], ['id'])
    op.alter_column('session', 'session_object',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=1000000000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session', 'session_object',
               existing_type=sa.Text(length=1000000000),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'assembly', type_='foreignkey')
    op.drop_column('assembly', 'user_id')
    # ### end Alembic commands ###
