"""removed metadata from table

Revision ID: 3d163bf2cb48
Revises: a863b31577d3
Create Date: 2023-01-17 21:38:18.470812

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3d163bf2cb48'
down_revision = 'a863b31577d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('cell_type', sa.String(length=64), nullable=True))
    op.drop_column('dataset', 'directionality')
    op.drop_column('dataset', 'derivationType')
    op.drop_column('dataset', 'valueType')
    op.drop_column('dataset', 'metadata_json')
    op.drop_column('dataset', 'method')
    op.drop_column('dataset', 'available_binsizes')
    op.drop_column('dataset', 'cellCycleStage')
    op.drop_column('dataset', 'protein')
    op.drop_column('dataset', 'normalization')
    op.alter_column('session', 'session_object',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=1000000000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session', 'session_object',
               existing_type=sa.Text(length=1000000000),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.add_column('dataset', sa.Column('normalization', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('dataset', sa.Column('protein', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('dataset', sa.Column('cellCycleStage', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('dataset', sa.Column('available_binsizes', mysql.VARCHAR(length=500), nullable=True))
    op.add_column('dataset', sa.Column('method', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('dataset', sa.Column('metadata_json', mysql.JSON(), nullable=True))
    op.add_column('dataset', sa.Column('valueType', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('dataset', sa.Column('derivationType', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('dataset', sa.Column('directionality', mysql.VARCHAR(length=64), nullable=True))
    op.drop_column('dataset', 'cell_type')
    # ### end Alembic commands ###
