"""Changed cluster number to category

Revision ID: 40bed80bef7c
Revises: 9e55daf37090
Create Date: 2021-10-18 09:26:44.585665

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '40bed80bef7c'
down_revision = '9e55daf37090'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('embedding_interval_data', 'cluster_number',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('session', 'session_object',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=1000000000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session', 'session_object',
               existing_type=sa.Text(length=1000000000),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.alter_column('embedding_interval_data', 'cluster_number',
               existing_type=sa.String(length=64),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
