"""added Obs/Exp cache table

Revision ID: 4cea26881323
Revises: 3c29653441d1
Create Date: 2021-11-17 11:51:18.718671

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4cea26881323'
down_revision = '3c29653441d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('obs_exp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('binsize', sa.Integer(), nullable=True),
    sa.Column('filepath', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_obs_exp_binsize'), 'obs_exp', ['binsize'], unique=False)
    op.create_index(op.f('ix_obs_exp_filepath'), 'obs_exp', ['filepath'], unique=False)
    op.alter_column('session', 'session_object',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=1000000000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session', 'session_object',
               existing_type=sa.Text(length=1000000000),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_obs_exp_filepath'), table_name='obs_exp')
    op.drop_index(op.f('ix_obs_exp_binsize'), table_name='obs_exp')
    op.drop_table('obs_exp')
    # ### end Alembic commands ###
