"""add intervals relationship to Task

Revision ID: 4e1aee093c2f
Revises: 9f0f54c889a2
Create Date: 2021-08-05 12:22:04.860308

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4e1aee093c2f'
down_revision = '9f0f54c889a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session', 'session_object',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=1000000000),
               existing_nullable=True)
    op.add_column('task', sa.Column('intervals_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'intervals', ['intervals_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'intervals_id')
    op.alter_column('session', 'session_object',
               existing_type=sa.Text(length=1000000000),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
