"""Added tables for association data

Revision ID: 56fdb3b41c8f
Revises: 7caac5b92423
Create Date: 2021-07-26 13:48:31.029466

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "56fdb3b41c8f"
down_revision = "7caac5b92423"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "association_interval_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("binsize", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=512), nullable=True),
        sa.Column("file_path", sa.String(length=512), nullable=True),
        sa.Column("value_type", sa.String(length=64), nullable=True),
        sa.Column("collection_id", sa.Integer(), nullable=True),
        sa.Column("intervals_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collection.id"],
        ),
        sa.ForeignKeyConstraint(
            ["intervals_id"],
            ["intervals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_association_interval_data_file_path"),
        "association_interval_data",
        ["file_path"],
        unique=False,
    )
    op.create_index(
        op.f("ix_association_interval_data_name"),
        "association_interval_data",
        ["name"],
        unique=False,
    )
    op.alter_column(
        "session",
        "session_object",
        existing_type=mysql.LONGTEXT(),
        type_=sa.Text(length=1000000000),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "session",
        "session_object",
        existing_type=sa.Text(length=1000000000),
        type_=mysql.LONGTEXT(),
        existing_nullable=True,
    )
    op.drop_index(
        op.f("ix_association_interval_data_name"),
        table_name="association_interval_data",
    )
    op.drop_index(
        op.f("ix_association_interval_data_file_path"),
        table_name="association_interval_data",
    )
    op.drop_table("association_interval_data")
    # ### end Alembic commands ###
