"""added filepahts for embedding 2d

Revision ID: 5b84649a8120
Revises: 5d8dd6f7a612
Create Date: 2021-10-11 09:20:56.068088

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5b84649a8120'
down_revision = '5d8dd6f7a612'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embedding_interval_data', sa.Column('cluster_id_path', sa.String(length=512), nullable=True))
    op.add_column('embedding_interval_data', sa.Column('feature_distribution_path', sa.String(length=512), nullable=True))
    op.add_column('embedding_interval_data', sa.Column('thumbnail_path', sa.String(length=512), nullable=True))
    op.create_index(op.f('ix_embedding_interval_data_cluster_id_path'), 'embedding_interval_data', ['cluster_id_path'], unique=False)
    op.create_index(op.f('ix_embedding_interval_data_feature_distribution_path'), 'embedding_interval_data', ['feature_distribution_path'], unique=False)
    op.create_index(op.f('ix_embedding_interval_data_thumbnail_path'), 'embedding_interval_data', ['thumbnail_path'], unique=False)
    op.alter_column('session', 'session_object',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=1000000000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session', 'session_object',
               existing_type=sa.Text(length=1000000000),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_embedding_interval_data_thumbnail_path'), table_name='embedding_interval_data')
    op.drop_index(op.f('ix_embedding_interval_data_feature_distribution_path'), table_name='embedding_interval_data')
    op.drop_index(op.f('ix_embedding_interval_data_cluster_id_path'), table_name='embedding_interval_data')
    op.drop_column('embedding_interval_data', 'thumbnail_path')
    op.drop_column('embedding_interval_data', 'feature_distribution_path')
    op.drop_column('embedding_interval_data', 'cluster_id_path')
    # ### end Alembic commands ###
