"""added chrom_arms field to Assembly

Revision ID: 60f956459e64
Revises: e01907557ec9
Create Date: 2021-08-25 09:16:00.176526

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '60f956459e64'
down_revision = 'e01907557ec9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assembly', sa.Column('chrom_arms', sa.Text(length=1000000000), nullable=True))
    op.alter_column('assembly', 'chrom_sizes',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=1000000000),
               existing_nullable=True)
    op.alter_column('session', 'session_object',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=1000000000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session', 'session_object',
               existing_type=sa.Text(length=1000000000),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.alter_column('assembly', 'chrom_sizes',
               existing_type=sa.Text(length=1000000000),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.drop_column('assembly', 'chrom_arms')
    # ### end Alembic commands ###
