"""added available binsizes to cooler

Revision ID: 64c188efd43d
Revises: a80efa60fd48
Create Date: 2021-04-12 20:48:30.321081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64c188efd43d'
down_revision = 'a80efa60fd48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('available_binsizes', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dataset', 'available_binsizes')
    # ### end Alembic commands ###
