"""added Individual interval data

Revision ID: 680384bd99b1
Revises: eb9a09406672
Create Date: 2021-01-22 15:16:33.717226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '680384bd99b1'
down_revision = 'eb9a09406672'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('individual_interval_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('binsize', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('file_path', sa.String(length=128), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('intervals_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.ForeignKeyConstraint(['intervals_id'], ['intervals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_individual_interval_data_file_path'), 'individual_interval_data', ['file_path'], unique=False)
    op.create_index(op.f('ix_individual_interval_data_name'), 'individual_interval_data', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_individual_interval_data_name'), table_name='individual_interval_data')
    op.drop_index(op.f('ix_individual_interval_data_file_path'), table_name='individual_interval_data')
    op.drop_table('individual_interval_data')
    # ### end Alembic commands ###
