"""Added timestamps to all tables for object creation

Revision ID: 6a3c43da20fd
Revises: 9b8b997feafb
Create Date: 2022-12-11 13:22:32.441767

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6a3c43da20fd'
down_revision = '9b8b997feafb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assembly', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('association_interval_data', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('average_interval_data', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('bed_file_metadata', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('collection', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('dataset', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('embedding_interval_data', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('individual_interval_data', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('intervals', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('organism', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('session', 'session_object',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=1000000000),
               existing_nullable=True)
    op.add_column('task', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created_at')
    op.drop_column('task', 'created_at')
    op.alter_column('session', 'session_object',
               existing_type=sa.Text(length=1000000000),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.drop_column('organism', 'created_at')
    op.drop_column('intervals', 'created_at')
    op.drop_column('individual_interval_data', 'created_at')
    op.drop_column('embedding_interval_data', 'created_at')
    op.drop_column('dataset', 'created_at')
    op.drop_column('collection', 'created_at')
    op.drop_column('bed_file_metadata', 'created_at')
    op.drop_column('average_interval_data', 'created_at')
    op.drop_column('association_interval_data', 'created_at')
    op.drop_column('assembly', 'created_at')
    # ### end Alembic commands ###
