"""switched fields for chrom sizesa and chrom arms to file paths

Revision ID: 6a9c1bc13457
Revises: 60f956459e64
Create Date: 2021-08-25 09:21:13.010462

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6a9c1bc13457'
down_revision = '60f956459e64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assembly', 'chrom_arms',
               existing_type=mysql.LONGTEXT(),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.alter_column('assembly', 'chrom_sizes',
               existing_type=mysql.LONGTEXT(),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.create_index(op.f('ix_assembly_chrom_arms'), 'assembly', ['chrom_arms'], unique=False)
    op.create_index(op.f('ix_assembly_chrom_sizes'), 'assembly', ['chrom_sizes'], unique=False)
    op.alter_column('session', 'session_object',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=1000000000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session', 'session_object',
               existing_type=sa.Text(length=1000000000),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_assembly_chrom_sizes'), table_name='assembly')
    op.drop_index(op.f('ix_assembly_chrom_arms'), table_name='assembly')
    op.alter_column('assembly', 'chrom_sizes',
               existing_type=sa.String(length=512),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.alter_column('assembly', 'chrom_arms',
               existing_type=sa.String(length=512),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
