"""added fields to collection

Revision ID: 7caac5b92423
Revises: 2615496ee71c
Create Date: 2021-07-22 10:57:10.291862

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "7caac5b92423"
down_revision = "2615496ee71c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("collection", sa.Column("kind", sa.String(length=256), nullable=True))
    op.alter_column(
        "session",
        "session_object",
        existing_type=mysql.LONGTEXT(),
        type_=sa.Text(length=1000000000),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "session",
        "session_object",
        existing_type=sa.Text(length=1000000000),
        type_=mysql.LONGTEXT(),
        existing_nullable=True,
    )
    op.drop_column("collection", "kind")
    # ### end Alembic commands ###
