"""No unique filepaths

Revision ID: 803c1cdf80d3
Revises: cb1e86c27b7f
Create Date: 2020-10-07 16:21:57.910821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '803c1cdf80d3'
down_revision = 'cb1e86c27b7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dataset_file_path', table_name='dataset')
    op.create_index(op.f('ix_dataset_file_path'), 'dataset', ['file_path'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dataset_file_path'), table_name='dataset')
    op.create_index('ix_dataset_file_path', 'dataset', ['file_path'], unique=1)
    # ### end Alembic commands ###
