"""made various name columns larger

Revision ID: 9132b0c70bdf
Revises: d3185dbf793f
Create Date: 2021-07-12 10:45:28.304870

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9132b0c70bdf'
down_revision = 'd3185dbf793f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('average_interval_data', 'file_path',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.alter_column('average_interval_data', 'name',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.alter_column('bed_file_metadata', 'file_path',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.alter_column('bed_file_metadata', 'name',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.alter_column('individual_interval_data', 'file_path',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.alter_column('individual_interval_data', 'name',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.alter_column('intervals', 'file_path',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.alter_column('intervals', 'file_path_sub_sample_index',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.alter_column('intervals', 'name',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.alter_column('task', 'description',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.alter_column('task', 'name',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.String(length=512),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'name',
               existing_type=sa.String(length=512),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=True)
    op.alter_column('task', 'description',
               existing_type=sa.String(length=512),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=True)
    op.alter_column('session', 'session_object',
               existing_type=sa.Text(length=1000000000),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.alter_column('intervals', 'name',
               existing_type=sa.String(length=512),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=True)
    op.alter_column('intervals', 'file_path_sub_sample_index',
               existing_type=sa.String(length=512),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=True)
    op.alter_column('intervals', 'file_path',
               existing_type=sa.String(length=512),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=True)
    op.alter_column('individual_interval_data', 'name',
               existing_type=sa.String(length=512),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=True)
    op.alter_column('individual_interval_data', 'file_path',
               existing_type=sa.String(length=512),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=True)
    op.alter_column('bed_file_metadata', 'name',
               existing_type=sa.String(length=512),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=True)
    op.alter_column('bed_file_metadata', 'file_path',
               existing_type=sa.String(length=512),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=True)
    op.alter_column('average_interval_data', 'name',
               existing_type=sa.String(length=512),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=True)
    op.alter_column('average_interval_data', 'file_path',
               existing_type=sa.String(length=512),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=True)
    # ### end Alembic commands ###
