"""Changed embedding data to relate to dataset instead of collection

Revision ID: 93912fdea0e2
Revises: 4cea26881323
Create Date: 2021-12-09 10:07:46.325553

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '93912fdea0e2'
down_revision = '4cea26881323'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embedding_interval_data', sa.Column('dataset_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'embedding_interval_data', 'dataset', ['dataset_id'], ['id'])
    op.alter_column('session', 'session_object',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=1000000000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session', 'session_object',
               existing_type=sa.Text(length=1000000000),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'embedding_interval_data', type_='foreignkey')
    op.drop_column('embedding_interval_data', 'dataset_id')
    # ### end Alembic commands ###
