"""add file path subsample column for Intervals

Revision ID: 9671576aface
Revises: 0fbd7ca83885
Create Date: 2021-06-01 12:07:07.540361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9671576aface'
down_revision = '0fbd7ca83885'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intervals', sa.Column('file_path_sub_sample_index', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_intervals_file_path_sub_sample_index'), 'intervals', ['file_path_sub_sample_index'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_intervals_file_path_sub_sample_index'), table_name='intervals')
    op.drop_column('intervals', 'file_path_sub_sample_index')
    # ### end Alembic commands ###
