"""added metadatajson, state

Revision ID: 991e58bc6e5b
Revises: f88fe53fcc63
Create Date: 2022-10-18 09:17:53.771484

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '991e58bc6e5b'
down_revision = 'f88fe53fcc63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('dataset_type', sa.String(length=64), nullable=False))
    op.add_column('dataset', sa.Column('metadata_json', sa.JSON(), nullable=True))
    op.add_column('dataset', sa.Column('upload_state', sa.String(length=64), nullable=False))
    op.alter_column('session', 'session_object',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=1000000000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session', 'session_object',
               existing_type=sa.Text(length=1000000000),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.drop_column('dataset', 'upload_state')
    op.drop_column('dataset', 'metadata_json')
    op.drop_column('dataset', 'dataset_type')
    # ### end Alembic commands ###
