"""many-to-many processing

Revision ID: 99a8595a8557
Revises: a85f00fc72ea
Create Date: 2021-09-10 09:32:15.586130

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '99a8595a8557'
down_revision = 'a85f00fc72ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset_dataset_preprocessing_table',
    sa.Column('dataset_region', sa.Integer(), nullable=True),
    sa.Column('dataset_feature', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_feature'], ['dataset.id'], ),
    sa.ForeignKeyConstraint(['dataset_region'], ['dataset.id'], )
    )
    op.drop_constraint('dataset_ibfk_3', 'dataset', type_='foreignkey')
    op.drop_column('dataset', 'processing_id')
    op.alter_column('session', 'session_object',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=1000000000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session', 'session_object',
               existing_type=sa.Text(length=1000000000),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.add_column('dataset', sa.Column('processing_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('dataset_ibfk_3', 'dataset', 'dataset', ['processing_id'], ['id'])
    op.drop_table('dataset_dataset_preprocessing_table')
    # ### end Alembic commands ###
