"""Added url ingest

Revision ID: 9b8b997feafb
Revises: 93912fdea0e2
Create Date: 2022-12-11 08:53:30.262375

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9b8b997feafb'
down_revision = '93912fdea0e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_repository',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('file_url', sa.String(length=512), nullable=True),
    sa.Column('auth_required', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('user__data_repository__credentials',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('repository_name', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=512), nullable=False),
    sa.Column('secret', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['repository_name'], ['data_repository.name'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'repository_name')
    )
    op.add_column('dataset', sa.Column('repository_name', sa.String(length=64), nullable=True))
    op.add_column('dataset', sa.Column('sample_id', sa.String(length=128), nullable=True))
    op.add_column('dataset', sa.Column('source_url', sa.String(length=512), nullable=True))
    op.create_foreign_key(None, 'dataset', 'data_repository', ['repository_name'], ['name'])
    op.alter_column('session', 'session_object',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=1000000000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session', 'session_object',
               existing_type=sa.Text(length=1000000000),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'dataset', type_='foreignkey')
    op.drop_column('dataset', 'source_url')
    op.drop_column('dataset', 'sample_id')
    op.drop_column('dataset', 'repository_name')
    op.drop_table('user__data_repository__credentials')
    op.drop_table('data_repository')
    # ### end Alembic commands ###
