"""added cluster_number field to embedding interval data

Revision ID: 9e55daf37090
Revises: e8d19f0e7979
Create Date: 2021-10-18 08:17:12.797765

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9e55daf37090'
down_revision = 'e8d19f0e7979'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embedding_interval_data', sa.Column('cluster_number', sa.Integer(), nullable=True))
    op.alter_column('session', 'session_object',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=1000000000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session', 'session_object',
               existing_type=sa.Text(length=1000000000),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.drop_column('embedding_interval_data', 'cluster_number')
    # ### end Alembic commands ###
