"""added metadata

Revision ID: a6af72741418
Revises: cc7a9f5681bc
Create Date: 2021-03-29 12:02:29.988218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a6af72741418"
down_revision = "cc7a9f5681bc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bed_file_metadata",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=True),
        sa.Column("file_path", sa.String(length=128), nullable=True),
        sa.Column("metadata_fields", sa.String(length=1024), nullable=True),
        sa.Column("dataset_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["dataset.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bed_file_metadata")
    # ### end Alembic commands ###
