"""added file path of indices to stackup table

Revision ID: a80efa60fd48
Revises: a6af72741418
Create Date: 2021-04-09 12:01:05.815056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a80efa60fd48'
down_revision = 'a6af72741418'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('individual_interval_data', sa.Column('file_path_indices_small', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_individual_interval_data_file_path_indices_small'), 'individual_interval_data', ['file_path_indices_small'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_individual_interval_data_file_path_indices_small'), table_name='individual_interval_data')
    op.drop_column('individual_interval_data', 'file_path_indices_small')
    # ### end Alembic commands ###
