"""removed index file from individual interval data since this is stored now on the interval level

Revision ID: c53312e68cc2
Revises: 9671576aface
Create Date: 2021-06-01 12:21:35.456263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c53312e68cc2'
down_revision = '9671576aface'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_individual_interval_data_file_path_indices_small', table_name='individual_interval_data')
    op.drop_column('individual_interval_data', 'file_path_indices_small')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('individual_interval_data', sa.Column('file_path_indices_small', sa.VARCHAR(length=128), nullable=True))
    op.create_index('ix_individual_interval_data_file_path_indices_small', 'individual_interval_data', ['file_path_indices_small'], unique=False)
    # ### end Alembic commands ###
