"""Added embedding interval data table

Revision ID: c57bedb77252
Revises: 4e1aee093c2f
Create Date: 2021-08-12 12:19:10.173906

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c57bedb77252'
down_revision = '4e1aee093c2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embedding_interval_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('binsize', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=512), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('value_type', sa.String(length=64), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('intervals_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.ForeignKeyConstraint(['intervals_id'], ['intervals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_embedding_interval_data_file_path'), 'embedding_interval_data', ['file_path'], unique=False)
    op.create_index(op.f('ix_embedding_interval_data_name'), 'embedding_interval_data', ['name'], unique=False)
    op.alter_column('session', 'session_object',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=1000000000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session', 'session_object',
               existing_type=sa.Text(length=1000000000),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_embedding_interval_data_name'), table_name='embedding_interval_data')
    op.drop_index(op.f('ix_embedding_interval_data_file_path'), table_name='embedding_interval_data')
    op.drop_table('embedding_interval_data')
    # ### end Alembic commands ###
