"""No unique datasetnames

Revision ID: cb1e86c27b7f
Revises: b40975b35573
Create Date: 2020-10-07 12:04:38.870251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb1e86c27b7f'
down_revision = 'b40975b35573'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dataset_dataset_name', table_name='dataset')
    op.create_index(op.f('ix_dataset_dataset_name'), 'dataset', ['dataset_name'], unique=False)
    op.drop_index('ix_pileup_name', table_name='pileup')
    op.create_index(op.f('ix_pileup_name'), 'pileup', ['name'], unique=False)
    op.drop_index('ix_pileupregion_name', table_name='pileupregion')
    op.create_index(op.f('ix_pileupregion_name'), 'pileupregion', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pileupregion_name'), table_name='pileupregion')
    op.create_index('ix_pileupregion_name', 'pileupregion', ['name'], unique=1)
    op.drop_index(op.f('ix_pileup_name'), table_name='pileup')
    op.create_index('ix_pileup_name', 'pileup', ['name'], unique=1)
    op.drop_index(op.f('ix_dataset_dataset_name'), table_name='dataset')
    op.create_index('ix_dataset_dataset_name', 'dataset', ['dataset_name'], unique=1)
    # ### end Alembic commands ###
