"""made text wider

Revision ID: d3185dbf793f
Revises: 32e4823ec454
Create Date: 2021-07-12 09:53:09.869554

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd3185dbf793f'
down_revision = '32e4823ec454'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'session_object')
    op.add_column('session', sa.Column('session_object', sa.Text(length=1000000000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'session_object')
    op.add_column('session', sa.Column('session_object', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
