"""added genotype and description columns

Revision ID: dd4f94c62b96
Revises: 60c0fa0ee852
Create Date: 2020-12-11 11:45:40.755314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd4f94c62b96'
down_revision = '60c0fa0ee852'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('description', sa.String(length=81), nullable=True))
    op.add_column('dataset', sa.Column('genotype', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dataset', 'genotype')
    op.drop_column('dataset', 'description')
    # ### end Alembic commands ###
