"""made some columns required

Revision ID: deda9d841f82
Revises: 991e58bc6e5b
Create Date: 2022-10-18 14:56:42.018794

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'deda9d841f82'
down_revision = '991e58bc6e5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dataset', 'dataset_name',
               existing_type=mysql.VARCHAR(length=512),
               nullable=False)
    op.alter_column('dataset', 'dataset_type',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.alter_column('dataset', 'file_path',
               existing_type=mysql.VARCHAR(length=512),
               nullable=False)
    op.alter_column('dataset', 'filetype',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.alter_column('dataset', 'public',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('dataset', 'sizeType',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.alter_column('dataset', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_index('ix_dataset_dataset_name', table_name='dataset')
    op.drop_index('ix_dataset_file_path', table_name='dataset')
    op.drop_index('ix_dataset_filetype', table_name='dataset')
    op.drop_constraint('dataset_ibfk_3', 'dataset', type_='foreignkey')
    op.alter_column('session', 'session_object',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=1000000000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session', 'session_object',
               existing_type=sa.Text(length=1000000000),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.create_foreign_key('dataset_ibfk_3', 'dataset', 'user', ['user_id'], ['id'])
    op.create_index('ix_dataset_filetype', 'dataset', ['filetype'], unique=False)
    op.create_index('ix_dataset_file_path', 'dataset', ['file_path'], unique=False)
    op.create_index('ix_dataset_dataset_name', 'dataset', ['dataset_name'], unique=False)
    op.alter_column('dataset', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('dataset', 'sizeType',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.alter_column('dataset', 'public',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('dataset', 'filetype',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.alter_column('dataset', 'file_path',
               existing_type=mysql.VARCHAR(length=512),
               nullable=True)
    op.alter_column('dataset', 'dataset_type',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.alter_column('dataset', 'dataset_name',
               existing_type=mysql.VARCHAR(length=512),
               nullable=True)
    # ### end Alembic commands ###
