"""sprint9 branch review

Revision ID: ebe631c74169
Revises: 
Create Date: 2022-09-30 09:20:54.350816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebe631c74169'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_repository',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('auth_required', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('organism',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('assembly',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=True),
    sa.Column('chrom_sizes', sa.String(length=512), nullable=True),
    sa.Column('chrom_arms', sa.String(length=512), nullable=True),
    sa.Column('organism_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organism_id'], ['organism.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assembly_chrom_arms'), 'assembly', ['chrom_arms'], unique=False)
    op.create_index(op.f('ix_assembly_chrom_sizes'), 'assembly', ['chrom_sizes'], unique=False)
    op.create_table('collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1024), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('kind', sa.String(length=256), nullable=True),
    sa.Column('processing_state', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_object', sa.Text(length=1000000000), nullable=True),
    sa.Column('created_utc', sa.DateTime(), nullable=False),
    sa.Column('session_type', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user__data_repository__credentials',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('repository_name', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=512), nullable=False),
    sa.Column('secret', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['repository_name'], ['data_repository.name'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'repository_name')
    )
    op.create_table('dataset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_name', sa.String(length=512), nullable=True),
    sa.Column('description', sa.String(length=81), nullable=True),
    sa.Column('perturbation', sa.String(length=64), nullable=True),
    sa.Column('assembly', sa.Integer(), nullable=True),
    sa.Column('cellCycleStage', sa.String(length=64), nullable=True),
    sa.Column('valueType', sa.String(length=64), nullable=True),
    sa.Column('method', sa.String(length=64), nullable=True),
    sa.Column('normalization', sa.String(length=64), nullable=True),
    sa.Column('derivationType', sa.String(length=64), nullable=True),
    sa.Column('sizeType', sa.String(length=64), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('protein', sa.String(length=64), nullable=True),
    sa.Column('directionality', sa.String(length=64), nullable=True),
    sa.Column('filetype', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('available_binsizes', sa.String(length=500), nullable=True),
    sa.Column('processing_state', sa.String(length=64), nullable=True),
    sa.Column('repository_name', sa.String(length=64), nullable=True),
    sa.Column('sample_id', sa.String(length=128), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['assembly'], ['assembly.id'], ),
    sa.ForeignKeyConstraint(['repository_name'], ['data_repository.name'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_dataset_name'), 'dataset', ['dataset_name'], unique=False)
    op.create_index(op.f('ix_dataset_file_path'), 'dataset', ['file_path'], unique=False)
    op.create_index(op.f('ix_dataset_filetype'), 'dataset', ['filetype'], unique=False)
    op.create_table('session_collection_assoc_table',
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], )
    )
    op.create_table('bed_file_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('metadata_fields', sa.String(length=1024), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collections_failed_table',
    sa.Column('dataset_region', sa.Integer(), nullable=True),
    sa.Column('collection_feature', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collection_feature'], ['collection.id'], ),
    sa.ForeignKeyConstraint(['dataset_region'], ['dataset.id'], ),
    sa.UniqueConstraint('dataset_region', 'collection_feature', name='uix_1')
    )
    op.create_table('collections_preprocessing_table',
    sa.Column('dataset_region', sa.Integer(), nullable=True),
    sa.Column('collection_feature', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collection_feature'], ['collection.id'], ),
    sa.ForeignKeyConstraint(['dataset_region'], ['dataset.id'], ),
    sa.UniqueConstraint('dataset_region', 'collection_feature', name='uix_1')
    )
    op.create_table('dataset_collection_assoc_table',
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], )
    )
    op.create_table('dataset_completed_table',
    sa.Column('dataset_region', sa.Integer(), nullable=True),
    sa.Column('dataset_feature', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_feature'], ['dataset.id'], ),
    sa.ForeignKeyConstraint(['dataset_region'], ['dataset.id'], ),
    sa.UniqueConstraint('dataset_region', 'dataset_feature', name='uix_1')
    )
    op.create_table('dataset_dataset_preprocessing_table',
    sa.Column('dataset_region', sa.Integer(), nullable=True),
    sa.Column('dataset_feature', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_feature'], ['dataset.id'], ),
    sa.ForeignKeyConstraint(['dataset_region'], ['dataset.id'], ),
    sa.UniqueConstraint('dataset_region', 'dataset_feature', name='uix_1')
    )
    op.create_table('dataset_failed_table',
    sa.Column('dataset_region', sa.Integer(), nullable=True),
    sa.Column('dataset_feature', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_feature'], ['dataset.id'], ),
    sa.ForeignKeyConstraint(['dataset_region'], ['dataset.id'], ),
    sa.UniqueConstraint('dataset_region', 'dataset_feature', name='uix_1')
    )
    op.create_table('intervals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=512), nullable=True),
    sa.Column('file_path_sub_sample_index', sa.String(length=512), nullable=True),
    sa.Column('windowsize', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intervals_file_path_sub_sample_index'), 'intervals', ['file_path_sub_sample_index'], unique=False)
    op.create_index(op.f('ix_intervals_name'), 'intervals', ['name'], unique=False)
    op.create_index(op.f('ix_intervals_windowsize'), 'intervals', ['windowsize'], unique=False)
    op.create_table('obs_exp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('binsize', sa.Integer(), nullable=True),
    sa.Column('filepath', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_obs_exp_binsize'), 'obs_exp', ['binsize'], unique=False)
    op.create_index(op.f('ix_obs_exp_filepath'), 'obs_exp', ['filepath'], unique=False)
    op.create_table('session_dataset_assoc_table',
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], )
    )
    op.create_table('association_interval_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('binsize', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=512), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('value_type', sa.String(length=64), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('intervals_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.ForeignKeyConstraint(['intervals_id'], ['intervals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_association_interval_data_file_path'), 'association_interval_data', ['file_path'], unique=False)
    op.create_index(op.f('ix_association_interval_data_name'), 'association_interval_data', ['name'], unique=False)
    op.create_table('average_interval_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('binsize', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=512), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('value_type', sa.String(length=64), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('intervals_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.ForeignKeyConstraint(['intervals_id'], ['intervals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_average_interval_data_file_path'), 'average_interval_data', ['file_path'], unique=False)
    op.create_index(op.f('ix_average_interval_data_name'), 'average_interval_data', ['name'], unique=False)
    op.create_table('embedding_interval_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('binsize', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=512), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('file_path_feature_values', sa.String(length=512), nullable=True),
    sa.Column('thumbnail_path', sa.String(length=512), nullable=True),
    sa.Column('cluster_id_path', sa.String(length=512), nullable=True),
    sa.Column('feature_distribution_path', sa.String(length=512), nullable=True),
    sa.Column('value_type', sa.String(length=64), nullable=True),
    sa.Column('normalization', sa.String(length=64), nullable=True),
    sa.Column('cluster_number', sa.String(length=64), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('intervals_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.ForeignKeyConstraint(['intervals_id'], ['intervals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_embedding_interval_data_cluster_id_path'), 'embedding_interval_data', ['cluster_id_path'], unique=False)
    op.create_index(op.f('ix_embedding_interval_data_feature_distribution_path'), 'embedding_interval_data', ['feature_distribution_path'], unique=False)
    op.create_index(op.f('ix_embedding_interval_data_file_path'), 'embedding_interval_data', ['file_path'], unique=False)
    op.create_index(op.f('ix_embedding_interval_data_file_path_feature_values'), 'embedding_interval_data', ['file_path_feature_values'], unique=False)
    op.create_index(op.f('ix_embedding_interval_data_name'), 'embedding_interval_data', ['name'], unique=False)
    op.create_index(op.f('ix_embedding_interval_data_thumbnail_path'), 'embedding_interval_data', ['thumbnail_path'], unique=False)
    op.create_table('individual_interval_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('binsize', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=512), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('file_path_small', sa.String(length=128), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('intervals_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.ForeignKeyConstraint(['intervals_id'], ['intervals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_individual_interval_data_file_path'), 'individual_interval_data', ['file_path'], unique=False)
    op.create_index(op.f('ix_individual_interval_data_file_path_small'), 'individual_interval_data', ['file_path_small'], unique=False)
    op.create_index(op.f('ix_individual_interval_data_name'), 'individual_interval_data', ['name'], unique=False)
    op.create_table('task',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('intervals_id', sa.Integer(), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.ForeignKeyConstraint(['intervals_id'], ['intervals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_name'), 'task', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_name'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_individual_interval_data_name'), table_name='individual_interval_data')
    op.drop_index(op.f('ix_individual_interval_data_file_path_small'), table_name='individual_interval_data')
    op.drop_index(op.f('ix_individual_interval_data_file_path'), table_name='individual_interval_data')
    op.drop_table('individual_interval_data')
    op.drop_index(op.f('ix_embedding_interval_data_thumbnail_path'), table_name='embedding_interval_data')
    op.drop_index(op.f('ix_embedding_interval_data_name'), table_name='embedding_interval_data')
    op.drop_index(op.f('ix_embedding_interval_data_file_path_feature_values'), table_name='embedding_interval_data')
    op.drop_index(op.f('ix_embedding_interval_data_file_path'), table_name='embedding_interval_data')
    op.drop_index(op.f('ix_embedding_interval_data_feature_distribution_path'), table_name='embedding_interval_data')
    op.drop_index(op.f('ix_embedding_interval_data_cluster_id_path'), table_name='embedding_interval_data')
    op.drop_table('embedding_interval_data')
    op.drop_index(op.f('ix_average_interval_data_name'), table_name='average_interval_data')
    op.drop_index(op.f('ix_average_interval_data_file_path'), table_name='average_interval_data')
    op.drop_table('average_interval_data')
    op.drop_index(op.f('ix_association_interval_data_name'), table_name='association_interval_data')
    op.drop_index(op.f('ix_association_interval_data_file_path'), table_name='association_interval_data')
    op.drop_table('association_interval_data')
    op.drop_table('session_dataset_assoc_table')
    op.drop_index(op.f('ix_obs_exp_filepath'), table_name='obs_exp')
    op.drop_index(op.f('ix_obs_exp_binsize'), table_name='obs_exp')
    op.drop_table('obs_exp')
    op.drop_index(op.f('ix_intervals_windowsize'), table_name='intervals')
    op.drop_index(op.f('ix_intervals_name'), table_name='intervals')
    op.drop_index(op.f('ix_intervals_file_path_sub_sample_index'), table_name='intervals')
    op.drop_table('intervals')
    op.drop_table('dataset_failed_table')
    op.drop_table('dataset_dataset_preprocessing_table')
    op.drop_table('dataset_completed_table')
    op.drop_table('dataset_collection_assoc_table')
    op.drop_table('collections_preprocessing_table')
    op.drop_table('collections_failed_table')
    op.drop_table('bed_file_metadata')
    op.drop_table('session_collection_assoc_table')
    op.drop_index(op.f('ix_dataset_filetype'), table_name='dataset')
    op.drop_index(op.f('ix_dataset_file_path'), table_name='dataset')
    op.drop_index(op.f('ix_dataset_dataset_name'), table_name='dataset')
    op.drop_table('dataset')
    op.drop_table('user__data_repository__credentials')
    op.drop_table('session')
    op.drop_table('collection')
    op.drop_index(op.f('ix_assembly_chrom_sizes'), table_name='assembly')
    op.drop_index(op.f('ix_assembly_chrom_arms'), table_name='assembly')
    op.drop_table('assembly')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('organism')
    op.drop_table('data_repository')
    # ### end Alembic commands ###
