"""added association tables for processing and failed collections

Revision ID: ee06748b98a3
Revises: 35ec45407a76
Create Date: 2021-09-10 15:06:37.388686

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ee06748b98a3'
down_revision = '35ec45407a76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections_failed_table',
    sa.Column('dataset_region', sa.Integer(), nullable=True),
    sa.Column('collection_feature', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collection_feature'], ['collection.id'], ),
    sa.ForeignKeyConstraint(['dataset_region'], ['dataset.id'], )
    )
    op.create_table('collections_preprocessing_table',
    sa.Column('dataset_region', sa.Integer(), nullable=True),
    sa.Column('collection_feature', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collection_feature'], ['collection.id'], ),
    sa.ForeignKeyConstraint(['dataset_region'], ['dataset.id'], )
    )
    op.alter_column('session', 'session_object',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=1000000000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session', 'session_object',
               existing_type=sa.Text(length=1000000000),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.drop_table('collections_preprocessing_table')
    op.drop_table('collections_failed_table')
    # ### end Alembic commands ###
