"""added filepath small to individual interval data

Revision ID: fef9655e7ab2
Revises: 680384bd99b1
Create Date: 2021-01-24 21:13:19.664718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fef9655e7ab2'
down_revision = '680384bd99b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('individual_interval_data', sa.Column('file_path_small', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_individual_interval_data_file_path_small'), 'individual_interval_data', ['file_path_small'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_individual_interval_data_file_path_small'), table_name='individual_interval_data')
    op.drop_column('individual_interval_data', 'file_path_small')
    # ### end Alembic commands ###
