"""pileupregion

Revision ID: 128595d4c011
Revises: 042ad8b8e5c6
Create Date: 2020-07-09 09:13:36.282791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '128595d4c011'
down_revision = '042ad8b8e5c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pileupregion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('file_path', sa.String(length=128), nullable=True),
    sa.Column('higlass_uuid', sa.String(length=64), nullable=True),
    sa.Column('windowsize', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pileupregion_file_path'), 'pileupregion', ['file_path'], unique=False)
    op.create_index(op.f('ix_pileupregion_higlass_uuid'), 'pileupregion', ['higlass_uuid'], unique=False)
    op.create_index(op.f('ix_pileupregion_name'), 'pileupregion', ['name'], unique=True)
    op.create_index(op.f('ix_pileupregion_windowsize'), 'pileupregion', ['windowsize'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pileupregion_windowsize'), table_name='pileupregion')
    op.drop_index(op.f('ix_pileupregion_name'), table_name='pileupregion')
    op.drop_index(op.f('ix_pileupregion_higlass_uuid'), table_name='pileupregion')
    op.drop_index(op.f('ix_pileupregion_file_path'), table_name='pileupregion')
    op.drop_table('pileupregion')
    # ### end Alembic commands ###
