baseURL = "http://localhost/docs/"
title = "HiCognition"
theme = "learn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "blue"
  disableLandingPageButton = true
  disableNextPrev = true
  disableInlineCopyToClipBoard = true

[[menu.shortcuts]]
name = "<i class='fas fa-tags'></i> Tags"
url = "/tags"
weight = 30