name: hicognition_base
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  # newest python
  - python=3.8.0
  # user required tools:
  - cooler >= 0.8.8
  - numpy==1.23.5
  - sortedcontainers >= 2.2.2
  - matplotlib >= 3.2.2
  - multiprocess >= 0.70.10
  - pairtools >= 0.3.0
  - pandas >= 1.0.5
  - pybedtools >= 0.8.1
  - pybigwig >=0.3.17
  - pysam >= 0.16.0.1
  - pydantic
  - scikit-learn >= 0.23.1 
  - scipy >= 1.5.0
  - seaborn >= 0.10.1
  - statsmodels >= 0.11.1
  - umap-learn
  - scikit-image
  # requirements for pairlib: 
  # - numpy
  - cython >= 0.29.20
  # requirements for bioframe:
  # - pandas 
  - six >=1.15.0
  - requests >= 2.24.0
  - pairix >= 0.3.7
  # requirements for cooltools:
  - h5py >= 2.10.0 
  - sparse
  - numba >= 0.48.0 
  - dask >= 2.19.0
  - click == 7.1.2
  - pytest >= 5.4.3
  # parquet support
  - pyensembl >= 1.8.7 
  - pyarrow >= 0.17.1
  - fastparquet >= 0.4.0 
  - inflection >= 0.5.1
  #more ngs tools
  - pip
  # flask related tools
  - apscheduler
  - pip:
      # flask packages
      - alembic==1.4.2
      - Babel==2.8.0
      - blinker==1.4
      - black
      - certifi==2020.6.20
      - chardet==3.0.4
      - dnspython==1.16.0
      - dominate==2.5.1
      - email-validator==1.1.1
      - Flask==1.1.2
      - Flask-Babel==1.0.0
      - Flask-Bootstrap==3.3.7.1
      - flask-cors
      - flask-sse
      - gunicorn
      - gevent
      - flask-httpauth==4.1.0
      - Flask-Login==0.5.0
      - Flask-Mail==0.9.1
      - Flask-Migrate==2.5.3
      - Flask-Moment==0.10.0
      - Flask-SQLAlchemy==2.4.3
      - Flask-WTF==0.14.3
      - guess-language-spirit==0.5.3
      - idna==2.9
      - itsdangerous==1.1.0
      - Jinja2==2.11.2
      - Mako==1.1.3
      - MarkupSafe==1.1.1
      - PyJWT==1.7.1
      - python-dateutil==2.8.1
      - python-dotenv==0.13.0
      - python-editor==1.0.4
      - pytz==2020.1
      - pymysql==1.0.2
      - pylama[all]
      - pylint
      - pylint-flask
      - pylint-flask-sqlalchemy
      - redis==3.5.3
      - requests==2.24.0
      - rq==1.8.1
      - six==1.15.0
      - SQLAlchemy==1.3.18
      - urllib3==1.25.9
      - visitor==0.1.3
      - Werkzeug==1.0.1
      - wincertstore==0.2
      - WTForms==2.3.1
      # HiC realted packages
      # - clodius - removed because needs very old pandas
      - pybbi
      - opencv-python-headless
      - pyhumps
