# This is a black&lint workflow that is manually triggered

name: Black and lint

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: workflow_dispatch
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Run python default tests
    - name: Run black
      run: |
        docker run gerlichlab/hicognition:latest black --check --extend-exclude /code/migrations /code/
    - name: Run pylint /app
    # More or less ignore for now
      run: |
        docker run gerlichlab/hicognition:latest pylint --disable=C0330 --fail-under=-3 /code/app/
    - name: Run pylint /tests
    # More or less ignore for now
      run: |
        docker run gerlichlab/hicognition:latest pylint --disable=C0330 --fail-under=-3 /code/tests/ 
    - name: Check code complexity
      run: |
        docker run gerlichlab/hicognition:latest pylama --linters mccabe /code/
