name: Run front-end tests
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CODE_DIR: "./"
    steps:
      - uses: actions/checkout@v2
      - name: Create directory structure
        run: |
          mkdir -p workdir/mysql
          mkdir keys
      - name: Start containers
        run: |
          docker-compose -f ./docker_front_end_test.yml up node
        env:
          DIR_FRONT_END: "./front_end/"